param(
    [int]$MaxItemsPerSection = 50,
    [int]$MaxAgeDays = 7
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$global:PSNativeCommandUseErrorActionPreference = $true

function UTS {
    (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
}

Write-Host "== CoBlock: Snapshot Local Context (Screenshots/Downloads/GitHub) ==" -ForegroundColor Yellow
Write-Host ""

$homePath = $HOME
$repoRoot = Join-Path $homePath 'Documents\GitHub\CoSteward'
if (-not (Test-Path $repoRoot)) {
    throw "CoSteward repo not found at: $repoRoot"
}
Set-Location $repoRoot

$intentDirRel = 'docs/intent/local'
$intentDirAbs = Join-Path $repoRoot $intentDirRel
if (-not (Test-Path $intentDirAbs)) {
    New-Item -ItemType Directory -Path $intentDirAbs -Force *> $null
}

$stamp     = UTS
$fileName  = "LocalContext_Snapshot_$stamp.md"
$fileRel   = Join-Path $intentDirRel $fileName
$fileAbs   = Join-Path $repoRoot $fileRel

$cutoff = (Get-Date).AddDays(-[math]::Abs($MaxAgeDays))

function Get-TableForPath {
    param(
        [string]$Title,
        [string]$Path,
        [string[]]$IncludeExtensions
    )

    if (-not (Test-Path $Path)) {
        return @(
            "### $Title",
            "",
            "_Path not found: `$Path`_",
            ""
        )
    }

    $items = Get-ChildItem -Path $Path -File -ErrorAction SilentlyContinue |
        Where-Object { $_.LastWriteTime -ge $cutoff } |
        Sort-Object LastWriteTime -Descending

    if ($IncludeExtensions -and $IncludeExtensions.Count -gt 0) {
        $items = $items | Where-Object { $IncludeExtensions -contains $_.Extension.ToLowerInvariant() }
    }

    $items = $items | Select-Object -First $MaxItemsPerSection

    if (-not $items) {
        return @(
            "### $Title",
            "",
            "_No files in window; cutoff: $($cutoff.ToString('yyyy-MM-dd HH:mm:ss'))_",
            ""
        )
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("### $Title")
    $lines.Add("")
    $lines.Add("| Name | LastWriteUtc | SizeKB | FullPath |")
    $lines.Add("| ---- | ------------ | ------ | -------- |")

    foreach ($f in $items) {
        $dt  = $f.LastWriteTimeUtc.ToString('yyyy-MM-ddTHH:mm:ssZ')
        $kb  = [math]::Round($f.Length / 1KB, 1)
        $fp  = $f.FullName
        $lines.Add("| $($f.Name) | $dt | $kb | `$fp` |")
    }

    $lines.Add("")
    return $lines
}

$screensPath = Join-Path $homePath 'Pictures\Screenshots'
$screensTbl  = Get-TableForPath -Title 'Screenshots (PNG, last few days)' -Path $screensPath -IncludeExtensions @('.png', '.jpg', '.jpeg')

$downloadsPath = Join-Path $homePath 'Downloads'
$downloadsTbl  = Get-TableForPath -Title 'Downloads (all types, last few days)' -Path $downloadsPath -IncludeExtensions @()

$githubRoot = Join-Path $homePath 'Documents\GitHub'
$repoLines  = [System.Collections.Generic.List[string]]::new()
$repoLines.Add("### GitHub Repos (branches)")
$repoLines.Add("")
$repoLines.Add("| Repo | Branch | Path |")
$repoLines.Add("| ---- | ------ | ---- |")

if (Test-Path $githubRoot) {
    Get-ChildItem -Path $githubRoot -Directory | ForEach-Object {
        $rPath = $_.FullName
        $name  = $_.Name
        $branch = ''
        try {
            $branch = git -C $rPath rev-parse --abbrev-ref HEAD 2>$null
        } catch {
            $branch = '(unknown)'
        }
        $repoLines.Add("| $name | $branch | `$rPath` |")
    }
    $repoLines.Add("")
} else {
    $repoLines.Add("_GitHub root not found: `$githubRoot`_")
    $repoLines.Add("")
}

$body = @()
$stampDisplay = $stamp
$body += "# Local Context Snapshot ($stampDisplay)"
$body += ""
$body += "This snapshot captures **metadata only** for local context:"
$body += "- Screenshots folder"
$body += "- Downloads folder"
$body += "- Local GitHub repos + branches"
$body += ""
$body += "_No file contents are copied into the repo by this CoBlock._"
$body += ""
$body += "Cutoff for file listings: $($cutoff.ToString('yyyy-MM-dd HH:mm:ss')) (local time)."
$body += ""
$body += "---"
$body += ""
$body += $screensTbl
$body += $downloadsTbl
$body += $repoLines
$body += "---"
$body += ""
$body += "Generated by: **Snapshot Local Context CoBlock (v1)**."
$body += ""

$body -join "`n" | Set-Content -Path $fileAbs -Encoding UTF8

Write-Host ("Wrote local context snapshot: {0}" -f $fileRel) -ForegroundColor Green

try {
    $hash = Get-FileHash -Path $fileAbs -Algorithm SHA256
    Write-Host ("SHA256: {0}" -f $hash.Hash) -ForegroundColor Cyan
} catch {
    Write-Host "WARN  Could not compute SHA256." -ForegroundColor DarkYellow
}
